version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/guerilla-trader-react
hooks:
  AfterInstall:
    - location: start_server.sh
      timeout: 300
      runas: root
    - location: start_server.sh
      timeout: 300
      runas: root
  BeforeInstall:
    - location: stop_server.sh
      timeout: 300
      runas: root
