export const SAVE_FUEL_SAVINGS = 'SAVE_FUEL_SAVINGS';
export const CALCULATE_FUEL_SAVINGS = 'CALCULATE_FUEL_SAVINGS';

export const MOCK_CREATE_TRADING_ACCOUNT_SUCCESS = 'MOCK_CREATE_TRADING_ACCOUNT_SUCCESS';
export const MOCK_UPDATE_TRADING_ACCOUNT_SUCCESS = 'MOCK_UPDATE_TRADING_ACCOUNT_SUCCESS';
export const MOCK_LOAD_TRADING_ACCOUNTS_SUCCESS = 'MOCK_LOAD_TRADING_ACCOUNTS_SUCCESS';

export const SEQUELIZE_CREATE_TRADING_ACCOUNT_SUCCESS = 'SEQUELIZE_CREATE_TRADING_ACCOUNT_SUCCESS';
export const SEQUELIZE_UPDATE_TRADING_ACCOUNT_SUCCESS = 'SEQUELIZE_UPDATE_TRADING_ACCOUNT_SUCCESS';
export const SEQUELIZE_LOAD_TRADING_ACCOUNTS_SUCCESS = 'SEQUELIZE_LOAD_TRADING_ACCOUNTS_SUCCESS';

export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';
