export const SAVE_FUEL_SAVINGS = 'SAVE_FUEL_SAVINGS';
export const CALCULATE_FUEL_SAVINGS = 'CALCULATE_FUEL_SAVINGS';

export const MOCK_CREATE_TRADING_ACCOUNT_SUCCESS = 'MOCK_CREATE_TRADING_ACCOUNT_SUCCESS';
export const MOCK_UPDATE_TRADING_ACCOUNT_SUCCESS = 'MOCK_UPDATE_TRADING_ACCOUNT_SUCCESS';
export const MOCK_LOAD_TRADING_ACCOUNTS_SUCCESS = 'MOCK_LOAD_TRADING_ACCOUNTS_SUCCESS';

export const CREATE_TRADING_ACCOUNT_SUCCESS = 'CREATE_TRADING_ACCOUNT_SUCCESS';
export const UPDATE_TRADING_ACCOUNT_SUCCESS = 'UPDATE_TRADING_ACCOUNT_SUCCESS';
export const LOAD_TRADING_ACCOUNTS_SUCCESS = 'LOAD_TRADING_ACCOUNTS_SUCCESS';

export const CREATE_MARKET_SUCCESS = 'CREATE_MARKET_SUCCESS';
export const UPDATE_MARKET_SUCCESS = 'UPDATE_MARKET_SUCCESS';
export const LOAD_MARKETS_SUCCESS = 'LOAD_MARKETS_SUCCESS';
export const MARKET_DATA_RECEIVED = 'MARKET_DATA_RECEIVED';

export const UPDATE_CURRENT_DATE = 'UPDATE_CURRENT_DATE';

export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';
