export const SAVE_FUEL_SAVINGS = 'SAVE_FUEL_SAVINGS';
export const CALCULATE_FUEL_SAVINGS = 'CALCULATE_FUEL_SAVINGS';

export const CREATE_TRADING_ACCOUNT_SUCCESS = 'CREATE_TRADING_ACCOUNT_SUCCESS';
export const UPDATE_TRADING_ACCOUNT_SUCCESS = 'UPDATE_TRADING_ACCOUNT_SUCCESS';
export const LOAD_TRADING_ACCOUNTS_SUCCESS = 'LOAD_TRADING_ACCOUNTS_SUCCESS';

export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';
